name: Miroir de DEV vers le dépôt DEV

on:
  push:
    branches:
      - dev

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : On récupère le code de la branche 'dev' du dépôt principal
      - name: Checkout code from dev branch
        uses: actions/checkout@v3
        with:
          # On s'assure de bien prendre le code qui vient d'être poussé
          ref: 'dev'
          # On récupère tout l'historique pour éviter les problèmes
          fetch-depth: 0

      # Étape 2 : On pousse le code vers le dépôt miroir 'jdecroocq/dev'
      - name: Push to dev repository
        run: |
          # On configure git pour qu'il pousse vers le dépôt miroir en utilisant ton jeton secret pour s'authentifier
          # C'est la commande la plus importante !
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/jdecroocq/dev.git
          
          # On pousse la branche locale 'dev' vers la branche 'main' du dépôt miroir.
          # Le '--force' est nécessaire pour que ce soit un miroir parfait.
          git push --force origin dev:main
