name: content-mirroring

on:
  push:
    branches:
      - content

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from content branch
        uses: actions/checkout@v3
        with:
          ref: 'content'
          fetch-depth: 0
          persist-credentials: false

      - name: Push to dev repository
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/jdecroocq/content.git
          git push --force origin content:main
