name: Mirror the content branch to the content repository

on:
  push:
    branches:
      - content

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'content'

      - name: Push to content repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: jdecroocq/content
          branch: main
          force: true
