name: Miroir de DEV vers le dépôt DEV

on:
  push:
    branches:
      - dev

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'dev'

      - name: Push to dev repository (alternative method)
        uses: cpina/github-action-push-to-another-repo@v1.5.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'jdecroocq'
          destination-repository-name: 'dev'
          target-branch: main
          force: true
